#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

HOST = data.get('host')
ESPOCRM_ADMIN_USERNAME = data.get('ESPOCRM_ADMIN_USERNAME', 'admin')
ESPOCRM_ADMIN_PASSWORD = data.get('ESPOCRM_ADMIN_PASSWORD', 'password')

app_config = {
    'ESPOCRM_ADMIN_USERNAME': ESPOCRM_ADMIN_USERNAME,
    'ESPOCRM_ADMIN_PASSWORD': ESPOCRM_ADMIN_PASSWORD,
    'ESPOCRM_SITE_URL': f'https://{HOST}',
}
agent.write_envfile("app.env", app_config)
ESPOCRM_CONFIG_USE_WEB_SOCKET = "true"
ESPOCRM_CONFIG_WEB_SOCKET_URL =  "ws://localhost:8081"
ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN =  "tcp://*:7777"
ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN =  "tcp://espocrm-websocket:7777"

websocket_config = {
    'ESPOCRM_CONFIG_USE_WEB_SOCKET': ESPOCRM_CONFIG_USE_WEB_SOCKET,
    'ESPOCRM_CONFIG_WEB_SOCKET_URL': ESPOCRM_CONFIG_WEB_SOCKET_URL,
    'ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN': ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN,
    'ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN': ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN,
}
agent.write_envfile("websocket.env", websocket_config)
#agent.dump_env()
